global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
- "django.rules"

scrape_configs:
- job_name: "django"
  static_configs:
  # This will work for a local Django
  - targets: ["localhost:8000"]	
